### PR TITLE
Add Azure/Anthropic/Replicate/Hugging Face models support - using liteLLM 

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for models from all the above mentioned providers using https://github.com/BerriAI/litellm
 
Here's a sample of how litellm completion is used:

```python
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@dhruv-anand-aintech can you take a look at this PR when you get the chance ?

**Comment by dhruv-anand-aintech** [comment]
Hey @ishaan-jaff thanks! This is a great addition. Could you also help us understand what would be required to support streaming in this server? We had had to make some changes to core openai library code, which we haven't added here.

**Comment by ishaan-jaff** [comment]
liteLLM supports streaming by default. If you pass `stream=True` we return a generator

**Comment by dhruv-anand-aintech** [comment]
Ok, I'll have to check it out. Since it is a proxy server I'm not sure if we are able to pass the generator from OpenAI to the end user correctly.

**Comment by dhruv-anand-aintech** [comment]
also, we'll need pricing information for the other APIs to be added here: https://github.com/AI-Northstar-Tech/openai-proxy/blob/main/proxy_app/utils.py

Do you have some kind of live pricing table that you refer to for this?

**Pull request merged**
